- name: jenkins jobs
  hosts: jenkins

  tasks:
    - name: create job1
      jenkins_job:
        host: http://localhost:8080
        state: present
        template: xml/job1.xml
        name: job1

    - name: check job1 idempotency
      jenkins_job:
        host: http://localhost:8080
        state: present
        template: xml/job1.xml
        name: job1

    - name: modify job1
      jenkins_job:
        host: http://localhost:8080
        state: present
        template: xml/job1-disabled.xml
        name: job1

    - name: delete job1
      jenkins_job:
        host: http://localhost:8080
        state: absent
        name: job1

    - name: create job2
      jenkins_job:
        host: http://localhost:8080
        state: present
        template: xml/job2.xml
        name: job2
